Update build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,7 +1,8 @@
 name: Build
-
 on:
   workflow_dispatch:
+  schedule:
+    - cron: '0 0 * * *'
 
 concurrency:
   group: build
@@ -20,14 +21,59 @@ jobs:
       packages: write
       contents: read
     steps:
+      - 
+        name: Run graphql query to get tag
+        uses: octokit/graphql-action@v2.x
+        id: latest_tag
+        with:
+          variables: |
+            repo: ${{ github.event.repository.name }}
+            owner: linuxboot
+          query: |
+            query tag($owner: String!, $repo: String!) {
+              repository(owner: $owner, name: $repo) {
+                refs(refPrefix: "refs/tags/", last: 1, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
+                  edges {
+                    node {
+                      name
+               } } } } }
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - 
+      - 
+        name: Parse tag from query output
+        run: |
+          #!/bin/bash
+          latest_tag=$(echo '${{ steps.latest_tag.outputs.data }}' | jq '.repository.refs.edges[][].name' -r)
+          [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" == "null" ]] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
+          echo "Found tag: \"${latest_tag}\"" 
+          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
+      - 
+        name: Check if the tag exists locally
+        uses: action-pack/tag-exists@v1
+        id: checkTag
+        with: 
+          tag: 'v${{ env.latest_tag }}'         
+      -
+        name: Finish when found
+        run: |
+          #!/bin/bash
+          beta="false"
+          
+          val="${{ steps.checkTag.outputs.exists }}"
+          echo "exists=${val}" >> $GITHUB_ENV
       -
         name: Checkout
+        if: env.exists == 'false'
         uses: actions/checkout@v5
         with:
           fetch-depth: 0
       -
         name: Docker metadata
         id: meta
+        if: env.exists == 'false'
         uses: docker/metadata-action@v5
         with:
           context: git
@@ -35,23 +81,26 @@ jobs:
             ${{ secrets.DOCKERHUB_REPO }}
             ghcr.io/${{ github.repository }}
           tags: |
-            type=raw,value=latest,priority=100
-            type=raw,value=${{ vars.MAJOR }}.${{ vars.MINOR }}
+            type=raw,value=latest,priority=100,enable=${{ env.beta == 'false' }}
+            type=raw,value=${{ env.latest_tag }}
           labels: |
             org.opencontainers.image.title=${{ vars.NAME }}
         env:
-          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index     
+          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
       - 
         name: Set up Docker Buildx
+        if: env.exists == 'false'
         uses: docker/setup-buildx-action@v3
       -
         name: Login into Docker Hub
+        if: env.exists == 'false'
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
         name: Login to GitHub Container Registry
+        if: env.exists == 'false'
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
@@ -59,6 +108,7 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       -
         name: Build Docker image
+        if: env.exists == 'false'
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -72,6 +122,7 @@ jobs:
             VERSION_ARG=${{ steps.meta.outputs.version }}
       - 
         name: Extract binary
+        if: env.exists == 'false'
         uses: shrink/actions-docker-extract@v3
         with:
           image: ${{ secrets.DOCKERHUB_REPO }}:latest
@@ -79,6 +130,7 @@ jobs:
           destination: "output"
       -
         name: Create a release
+        if: env.exists == 'false'
         uses: action-pack/github-release@v2
         with:
           tag: "v${{ steps.meta.outputs.version }}"
@@ -86,18 +138,15 @@ jobs:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
       -
         name: Update release
+        if: env.exists == 'false'
         uses: AButler/upload-release-assets@v3.0
         with:
           files: 'output/utk.bin'
           release-tag: "v${{ steps.meta.outputs.version }}"
           repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
       -
-        name: Increment version variable
-        uses: action-pack/bump@v2
-        with:
-          token: ${{ secrets.REPO_ACCESS_TOKEN }}
-      -
         name: Send mail
+        if: env.exists == 'false'
         uses: action-pack/send-mail@v1
         with:
           to: ${{secrets.MAILTO}}
